ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS is_draft boolean NOT NULL DEFAULT false;
ALTER TABLE public.clients
  ALTER COLUMN company_name DROP NOT NULL,
  ALTER COLUMN website DROP NOT NULL,
  ALTER COLUMN company_description DROP NOT NULL,
  ALTER COLUMN industry DROP NOT NULL,
  ALTER COLUMN contact_person DROP NOT NULL,
  ALTER COLUMN street DROP NOT NULL,
  ALTER COLUMN postal_code DROP NOT NULL,
  ALTER COLUMN city DROP NOT NULL,
  ALTER COLUMN vat_id DROP NOT NULL,
  ALTER COLUMN phone DROP NOT NULL,
  ALTER COLUMN email DROP NOT NULL,
  ALTER COLUMN greeting_text DROP NOT NULL;