// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://erwuhvouxkaxczzbjrle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyd3Vodm91eGtheGN6emJqcmxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQyMTMwNDQsImV4cCI6MjA5OTc4OTA0NH0.YkF9yhfAcmDVmj2LG50AxMI7lHaUnAnBBkq2gr-RT2I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});